# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position controllers for Gazebo simulation
fr5_position_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    j1: {trajectory: 0.1, goal: 0.1}
    j2: {trajectory: 0.1, goal: 0.1}
    j3: {trajectory: 0.1, goal: 0.1}
    j4: {trajectory: 0.1, goal: 0.1}
    j5: {trajectory: 0.1, goal: 0.1}
    j6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10
  gains:
    j1:
      p: 40
      d: 20
      i: 0
      i_clamp: 0
    j2:
      p: 80
      d: 40
      i: 0
      i_clamp: 0
    j3:
      p: 60
      d: 30
      i: 0
      i_clamp: 0
    j4:
      p: 20
      d: 10
      i: 0.05
      i_clamp: 0.5
    j5:
      p: 20
      d: 10
      i: 0.05
      i_clamp: 0.5
    j6:
      p: 20
      d: 10
      i: 0.1
      i_clamp: 1
