fr5_position_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  gains:
    j1:
      p: 400
      d: 20
      i: 0
      i_clamp: 0
    j2:
      p: 800
      d: 40
      i: 0
      i_clamp: 0
    j3:
      p: 600
      d: 30
      i: 0
      i_clamp: 0
    j4:
      p: 100
      d: 5
      i: 0
      i_clamp: 0
    j5:
      p: 100
      d: 5
      i: 0
      i_clamp: 0
    j6:
      p: 20
      d: 1
      i: 0
      i_clamp: 0