arm_effort_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6

  state_publish_rate: 100
  action_monitor_rate: 20

  constraints:
    goal_time: 3.0
    stopped_velocity_tolerance: 0.1
    j1: {trajectory: 0.50, goal: 0.10}
    j2: {trajectory: 0.50, goal: 0.10}
    j3: {trajectory: 0.50, goal: 0.10}
    j4: {trajectory: 0.50, goal: 0.15}
    j5: {trajectory: 0.50, goal: 0.15}
    j6: {trajectory: 0.50, goal: 0.15}
  gains:
    j1:
      p: 800
      d: 20
      i: 1.0
      i_clamp: 50
    j2:
      p: 4000
      d: 200
      i: 1.0
      i_clamp: 150
    j3:
      p: 4000
      d: 150
      i: 1.0
      i_clamp: 100
    j4:
      p: 1000
      d: 50
      i: 1.0
      i_clamp: 30
    j5:
      p: 300
      d: 15
      i: 1.0
      i_clamp: 25
    j6:
      p: 300
      d: 15
      i: 1.0
      i_clamp: 15

  stop_trajectory_duration: 0.5
  allow_partial_joints_goal: true