arm_effort_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.05
    j1: {trajectory: 0.30, goal: 0.05}
    j2: {trajectory: 0.30, goal: 0.05}
    j3: {trajectory: 0.30, goal: 0.05}
    j4: {trajectory: 0.30, goal: 0.08}
    j5: {trajectory: 0.30, goal: 0.08}
    j6: {trajectory: 0.30, goal: 0.08}
  gains:
    j1:
      p: 526
      d: 2
      i: 0.15
      i_clamp: 18
    j2:
      p: 1906
      d: 98
      i: 0.25
      i_clamp: 40
    j3:
      p: 2248
      d: 5.4
      i: 0.19
      i_clamp: 30
    j4:
      p: 310
      d: 15
      i: 0
      i_clamp: 0
    j5:
      p: 305
      d: 9
      i: 0
      i_clamp: 0
    j6:
      p: 156
      d: 3.14
      i: 0
      i_clamp: 0